name = "artemis-tracker"
account_id = "c3b373ae8a90a6494e520f962bdf462b"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "public"

[[routes]]
pattern = "artemis-tracker.meandmybadself.com"
custom_domain = true
